name: google_map
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.5.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  material_floating_search_bar_2: ^0.5.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
